services:
  nginx:
    image: nginx:alpine
    ports:
      - 8888:80
    volumes:
      - app:/app
      - ./nginx:/etc/nginx/conf.d
  php:
    build: .
    container_name: php-fpm
    volumes:
      - app:/app
    expose:
      - 9000
volumes:
  app: