services:
  nginx:
    image: nginx:alpine
    ports:
      - 80
    volumes:
      - app:/app
      - ./nginx:/etc/nginx/conf.d
    networks:
      - dokploy-network
  php:
    build: .
    volumes:
      - app:/app
    networks:
      - dokploy-network
volumes:
  app:
networks:
  dokploy-network:
    external: true