services:
  nginx:
    image: nginx:alpine
    ports:
      - 8888:80
    volumes:
      - app:/app
      - ./nginx:/etc/nginx/conf.d
    links:
      - php
  php:
    build: .
    volumes:
      - app:/app
volumes:
  app: